language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  # gearman
  - sudo apt-get remove gearman-job-server
  - sudo apt-get install gearman-job-server libgearman2
  - printf "\n"| pecl install gearman
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - gearmand -d
  - phpunit
